version: '3.3'
services:
  rmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    network_mode: "host"

  flower:
    image: mher/flower:0.9.5
    network_mode: "host"
    depends_on: 
      - rmq 
    environment:
      - CELERY_BROKER_URL=pyamqp://admin:admin@localhost:5672//
      - FLOWER_PORT=8888
