version: '3.3'
services:
  worker:
    build:
      context: .
      dockerfile: ./dockerfile
    working_dir: /home/fenics/shared/
    command:
      - "./init.sh && ./entry.sh"
    network_mode: "host"
    environment:
      - RMQIP=localhost

